---

- hosts: all
  become: true
  tasks:

  - name: update repo index, install apache and php package
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"